# Generated by Django 4.0.6 on 2022-09-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineadonacion',
            options={'ordering': ['id'], 'verbose_name': 'Linea Donacion', 'verbose_name_plural': 'Lineas Donaciones'},
        ),
    ]
